sudo: required
services:
    - docker

before_install:
    - docker build -t ersergeant/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ersergeant/react-test npm test

after_success:
    - docker build -t ersergeant/multi-client ./client
    - docker build -t ersergeant/multi-nginx ./nginx
    - docker build -t ersergeant/multi-server ./server
    - docker build -t ersergeant/multi-worker ./worker
# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD"   | docker login -u "$DOCKER_ID" --password-stdin 

# Take those images and push them to docker hub
    - docker push ersergeant/multi-client
    - docker push ersergeant/multi-nginx
    - docker push ersergeant/multi-server
    - docker push ersergeant/multi-worker